name: torneo_app
description: Aplicación para la gestión de torneos deportivos.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_dotenv: ^5.1.0
  intl: ^0.20.2
  fl_chart: ^0.71.0
  video_player: ^2.7.0
  cupertino_icons: ^1.0.6
  dio: ^5.6.0
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.2
  url_launcher: ^6.3.0
  table_calendar: ^3.1.4  # ✅ Alternativa gratuita y funcional

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_uide.png